using System;
using System.Collections.Generic;

namespace SignalrTypescriptGenerator.Models {

  public class TypesModel {

    public string LastGenerated => $"// Autogenerated by SignalrTypescriptGenerator.exe at {DateTimeOffset.Now:yyyy-MM-ddTHH:mm:sszzz}";

    public IEnumerable<ITypeInfo> TypeInfos { get; set; }

  }

}